# Generated by Django 2.0.4 on 2018-04-24 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chronocard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('work_start_date', models.DateTimeField()),
                ('work_end_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='EventShift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='chronocard.Event')),
            ],
        ),
        migrations.CreateModel(
            name='EventUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_time', models.FloatField(default=0)),
                ('badge_id', models.CharField(max_length=16)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='chronocard.Event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=64)),
                ('location', models.CharField(max_length=64)),
                ('instruction', models.TextField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='chronocard.Event')),
            ],
        ),
        migrations.AddField(
            model_name='eventshift',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='chronocard.Location'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='event_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='chronocard.EventUser'),
        ),
    ]
