# Generated by Django 2.0.4 on 2018-05-29 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronocard', '0002_auto_20180424_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='work_end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='work_start_date',
            field=models.DateField(),
        ),
    ]
