# Generated by Django 2.0.4 on 2018-06-25 20:29

from django.db import migrations, models
from django.contrib.auth.models import Group

def add_deputies_group(apps, schema_editor):
    deputies_group = Group(name='deputies')
    deputies_group.save()


class Migration(migrations.Migration):

    dependencies = [
        ('chronocard', '0003_auto_20180529_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventuser',
            name='total_time',
        ),
        migrations.AlterField(
            model_name='checkin',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(add_deputies_group),

    ]
