# Generated by Django 2.0.4 on 2018-06-25 20:29

from django.db import migrations, models
from django.contrib.auth.models import Group, Permission

def add_deputies_group(apps, schema_editor):
    # Group = apps.get_model('auth', 'Group')
    deputies_group = Group(name='deputies')
    deputies_group.save()

    checkin_perms = Permission.objects.filter(codename__contains='checkin')
    for p in checkin_perms:
        deputies_group.permissions.add(p)


def revert_deputies_group(apps, schema_editor):
    # Group = apps.get_model('auth', 'Group')
    deputy_group = Group(name='deputies')
    deputy_group.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('chronocard', '0003_auto_20180529_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventuser',
            name='total_time',
        ),
        migrations.AlterField(
            model_name='checkin',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(add_deputies_group, revert_deputies_group),

    ]
