# Generated by Django 2.1 on 2018-08-20 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronocard', '0006_event_time_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventuser',
            name='badge_id',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
