# Generated by Django 2.1 on 2018-08-20 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronocard', '0007_auto_20180819_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventuser',
            name='badge_id',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
